# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeworkset.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets

from gui_utils import TeacherHomeworkButton

class Problem_widget(QtWidgets.QWidget):

    def __init__(self, parent, dex, widgetbar):

        super(Problem_widget,self).__init__()
        self.dex = dex
        self.widgetbar = widgetbar
        self.parent = parent
        self.setupUi(self)
        self.retranslateUi(self)
        self.label.setText("题目:{:3d}".format(dex+1))
        self.textBrowser.setText('Loading....')
        self.proscore = 0

        self.lineEdit.textChanged.connect(self.cal_total_score)

    def cal_total_score(self):
        if not self.lineEdit.text():
            self.parent.total_score += 0 - self.proscore
            self.proscore = 0
            self.parent.label_3.setText("总分：{:d}".format(self.parent.total_score))
        elif self.lineEdit.text().isdigit():
            self.parent.total_score += int(self.lineEdit.text())-self.proscore
            self.proscore = int(self.lineEdit.text())
            self.parent.label_3.setText("总分：{:d}".format(self.parent.total_score))

        else:
            QtWidgets.QMessageBox.information(self, '输入警告', '请勿在输入非数字分值', QtWidgets.QMessageBox.Yes)
            self.lineEdit.setText('')
            self.parent.total_score -= self.proscore
        # print(self.lineEdit.text())

    def adjust_bbox_width(self):
        height = self.textBrowser.document().size().height() + self.textBrowser.contentsMargins().top() + self.textBrowser.contentsMargins().bottom()
        self.textBrowser.setFixedHeight(height)
        # self.widgetbar.adjustSize()
        self.adjustSize()
        self.widgetbar.setSizeHint(self.size())

    def setupUi(self, Form):
        Form.setObjectName("Form")
        # Form.resize(467, 168)
        self.setFixedWidth(444)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 9, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(220, 9, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(290, 10, 71, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setFixedWidth(351)
        self.textBrowser.setObjectName("textBrowser")

        self.textBrowser.setGeometry(QtCore.QRect(50, 60, self.textBrowser.size().width(), self.textBrowser.size().height()))
        self.textBrowser.setText('Loading....')

        self.textBrowser.textChanged.connect(self.adjust_bbox_width)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "题目"))
        self.label_2.setText(_translate("Form", "分值："))

class Ui_Form(QtWidgets.QWidget):
    def __init__(self, parent, questions):
        super(Ui_Form,self).__init__()
        self.parent = parent
        self.questions = questions
        self.total_score = 0

        self.setupUi(self)
        self.retranslateUi(self)

        self.pushButton_2.clicked.connect(self.close)
        self.pushButton.clicked.connect(self.confirm_create_homework)

    def confirm_create_homework(self):
        # teacher_release_homework(self, homework_name, ddl, class_id, questions_points_and_questiontypes)
        uid, homework_name, ddl_date, ddl_time, class_id = self.parent.db.account2userid(self.parent.account.id), self.textEdit.text(), self.dateTimeEdit.date(), self.dateTimeEdit.time(), self.parent.account.group
        ddl = "{:d}-{:d}-{:d} {:d}:{:d}:{:d}".format(ddl_date.year(), ddl_date.month(), ddl_date.day(), ddl_time.hour(), ddl_time.minute(), ddl_time.second())
        qpq = []
        for i in range(len(self.questions)):
            point = self.question_widgets[i].lineEdit.text()
            if not point.isdigit():
                point = '0'
            qpq.append([self.questions[i][1], int(point), self.questions[i][4]])
        # print(homework_name, ddl, class_id, type(homework_name), type(class_id))
        if not len(homework_name):
            QtWidgets.QMessageBox.information(self, '创建失败', '作业名不能为空', QtWidgets.QMessageBox.Yes)
            return
        if not len(qpq):
            QtWidgets.QMessageBox.information(self, '创建失败', '没有选择任何题目', QtWidgets.QMessageBox.Yes)
            return
        import time
        now_date = time.strftime('%Y-%m-%d %H:%M:%S')

        ddate = "{:04d}-{:02d}-{:02d} {:02d}:{:02d}:{:02d}".format(ddl_date.year(), ddl_date.month(), ddl_date.day(), ddl_time.hour(), ddl_time.minute(), ddl_time.second())
        if now_date > ddate:
            QtWidgets.QMessageBox.information(self, '创建失败', '截止时间已过', QtWidgets.QMessageBox.Yes)
            return
        self.parent.db.teacher_release_homework(uid, homework_name, ddl, class_id, qpq)
        self.close()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(643, 534)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 139, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 139, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 139, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 139, 87))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(90, 50, 471, 271))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 359, 91, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QLineEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(170, 349, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = TeacherHomeworkButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 460, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = TeacherHomeworkButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 460, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 409, 91, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Form)
        # self.dateTimeEdit = CalendarExample()
        self.dateTimeEdit.setGeometry(QtCore.QRect(170, 400, 411, 31))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(441, 15, 161, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_3.setPalette(palette)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        # self.questions = []
        #
        #
        # self.newwidget = QtWidgets.QListWidgetItem()
        # self.questions.append(Problem_widget(self, self.newwidget))
        # self.newwidget.setSizeHint(self.questions[-1].size())
        # self.listWidget.addItem(self.newwidget)
        # self.listWidget.setItemWidget(self.newwidget, self.questions[-1])

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.question_widgets, self.question_frames = [], []
        for i in range(len(self.questions)):
            self.question_frames.append(QtWidgets.QListWidgetItem())
            self.question_widgets.append(Problem_widget(self, i, self.question_frames[-1]))
            self.listWidget.addItem(self.question_frames[-1])
            self.listWidget.setItemWidget(self.question_frames[-1], self.question_widgets[-1])

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "作业名称:"))
        self.pushButton.setText(_translate("Form", "确认发布"))
        self.pushButton_2.setText(_translate("Form", "取消"))
        self.label_2.setText(_translate("Form", "截止时间:"))
        self.label_3.setText(_translate("Form", "总分：{:d}".format(0)))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)

    ui = Ui_Form()
    ui.show()

    sys.exit(app.exec_())